import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:iconsax/iconsax.dart';

class IconColorStorage{
  static const Map<String, Map<String, dynamic>> icons = {
    'Common': {
      'folder': Iconsax.folder,
      'heart': Iconsax.heart,
      'star': Iconsax.star,
      'home': Iconsax.home,
      'calendar': Iconsax.calendar,
      'note': Iconsax.note,
      'clock': Iconsax.clock,
      'bookmark': FontAwesomeIcons.bookmark,
      'bell': FontAwesomeIcons.bell,
      'check': FontAwesomeIcons.check,
      'flag': Iconsax.flag,
      'location': Iconsax.location,
      'message': Iconsax.message,
    },
    'Food & Drink': {
      'coffee': Iconsax.coffee,
      'utensils': FontAwesomeIcons.utensils,
      'burger': FontAwesomeIcons.burger,
      'pizza': FontAwesomeIcons.pizzaSlice,
      'ice_cream': FontAwesomeIcons.iceCream,
      'cookie': FontAwesomeIcons.cookie,
      'apple': FontAwesomeIcons.appleWhole,
      'cheese': FontAwesomeIcons.cheese,
      'bread': FontAwesomeIcons.breadSlice,
      'wine': FontAwesomeIcons.wineBottle,
      'cocktail': FontAwesomeIcons.martiniGlassCitrus,
      'tea': FontAwesomeIcons.mugSaucer,
      'cake': Iconsax.cake,
      'salad': FontAwesomeIcons.leaf,
      'soup': FontAwesomeIcons.bowlRice,
      'steak': FontAwesomeIcons.bacon,
    },
    'Transport': {
      'car': Iconsax.car,
      'airplane': Iconsax.airplane,
      'bicycle': FontAwesomeIcons.bicycle,
      'train': FontAwesomeIcons.train,
      'bus': FontAwesomeIcons.bus,
      'ship': FontAwesomeIcons.ship,
      'motorcycle': FontAwesomeIcons.motorcycle,
      'helicopter': FontAwesomeIcons.helicopter,
      'truck': FontAwesomeIcons.truck,
      'subway': FontAwesomeIcons.trainSubway,
    },
    'Shopping': {
      'cart': Iconsax.shopping_cart,
      'bag': Iconsax.bag,
      'box': Iconsax.box,
      'gift': Iconsax.gift,
      'tag': FontAwesomeIcons.tag,
      'shop': Iconsax.shop,
      'receipt': FontAwesomeIcons.receipt,
      'wallet': Iconsax.wallet,
      'credit_card': FontAwesomeIcons.creditCard,
      'money': FontAwesomeIcons.moneyBill,
    },
    'Health & Fitness': {
      'dumbbell': FontAwesomeIcons.dumbbell,
      'heart_pulse': FontAwesomeIcons.heartPulse,
      'running': FontAwesomeIcons.personRunning,
      'meditation': FontAwesomeIcons.spa,
      'health': Iconsax.health,
      'pills': FontAwesomeIcons.pills,
      'suitcase_medical': FontAwesomeIcons.suitcaseMedical,
      'stethoscope': FontAwesomeIcons.stethoscope,
      'scale': FontAwesomeIcons.weightScale,
      'yoga': FontAwesomeIcons.personPraying,
      'swimming': FontAwesomeIcons.personSwimming,
      'biking': FontAwesomeIcons.personBiking,
    },
    'Education': {
      'book': Iconsax.book,
      'book_open': FontAwesomeIcons.bookOpen,
      'graduation_cap': FontAwesomeIcons.graduationCap,
      'chalkboard': FontAwesomeIcons.chalkboard,
      'pencil': FontAwesomeIcons.pencil,
      'ruler': FontAwesomeIcons.ruler,
      'calculator': FontAwesomeIcons.calculator,
      'teacher': Iconsax.teacher,
      'microscope': FontAwesomeIcons.microscope,
      'flask': FontAwesomeIcons.flask,
      'atom': FontAwesomeIcons.atom,
      'brain': FontAwesomeIcons.brain,
    },
    'Work & Business': {
      'briefcase': Iconsax.briefcase,
      'chart': Iconsax.chart,
      'chart_line': FontAwesomeIcons.chartLine,
      'task': Iconsax.task_square,
      'building': Iconsax.building,
      'presentation': FontAwesomeIcons.display,
      'handshake': FontAwesomeIcons.handshake,
      'people': FontAwesomeIcons.users,
      'bank': FontAwesomeIcons.buildingColumns,
      'document': FontAwesomeIcons.fileLines,
      'signature': FontAwesomeIcons.signature,
      'network': FontAwesomeIcons.networkWired,
    },
    'Technology': {
      'laptop': FontAwesomeIcons.laptop,
      'mobile': FontAwesomeIcons.mobile,
      'tablet': FontAwesomeIcons.tablet,
      'desktop': FontAwesomeIcons.desktop,
      'code': FontAwesomeIcons.code,
      'microchip': FontAwesomeIcons.microchip,
      'server': FontAwesomeIcons.server,
      'database': FontAwesomeIcons.database,
      'wifi': FontAwesomeIcons.wifi,
      'keyboard': FontAwesomeIcons.keyboard,
      'mouse': FontAwesomeIcons.computerMouse,
      'printer': FontAwesomeIcons.print,
    },
    'Entertainment': {
      'music': Iconsax.music,
      'video': Iconsax.video,
      'game': Iconsax.game,
      'headphone': Iconsax.headphone,
      'film': FontAwesomeIcons.film,
      'ticket': Iconsax.ticket,
      'theater': FontAwesomeIcons.masksTheater,
      'tv': FontAwesomeIcons.tv,
      'camera': Iconsax.camera,
      'dice': FontAwesomeIcons.dice,
      'gamepad': FontAwesomeIcons.gamepad,
      'vr_headset': FontAwesomeIcons.vrCardboard,
    },
    'Travel & Places': {
      'map': Iconsax.map,
      'compass': FontAwesomeIcons.compass,
      'hotel': FontAwesomeIcons.bed,
      'suitcase': FontAwesomeIcons.suitcaseRolling,
      'passport': FontAwesomeIcons.passport,
      'beach': FontAwesomeIcons.umbrellaBeach,
      'mountain': FontAwesomeIcons.mountain,
      'camping': FontAwesomeIcons.campground,
      'binoculars': FontAwesomeIcons.binoculars,
      'earth': FontAwesomeIcons.earthAmericas,
      'signpost': FontAwesomeIcons.signsPost,
      'luggage_cart': FontAwesomeIcons.cartFlatbedSuitcase,
    },
    'Nature & Weather': {
      'tree': Iconsax.tree,
      'pet': Iconsax.pet,
      'plant': FontAwesomeIcons.seedling,
      'sun': FontAwesomeIcons.sun,
      'moon': FontAwesomeIcons.moon,
      'cloud': FontAwesomeIcons.cloud,
      'snowflake': FontAwesomeIcons.snowflake,
      'fire': FontAwesomeIcons.fire,
      'wind': FontAwesomeIcons.wind,
      'rainbow': FontAwesomeIcons.rainbow,
      'leaf': FontAwesomeIcons.leaf,
      'water': FontAwesomeIcons.water,
    },
    'Home & Living': {
      'couch': FontAwesomeIcons.couch,
      'bed': FontAwesomeIcons.bed,
      'chair': FontAwesomeIcons.chair,
      'soap': FontAwesomeIcons.soap,
      'shower': FontAwesomeIcons.shower,
      'toilet': FontAwesomeIcons.toilet,
      'lightbulb': FontAwesomeIcons.lightbulb,
      'broom': FontAwesomeIcons.broom,
      'fan': FontAwesomeIcons.fan,
      'kitchen': FontAwesomeIcons.kitchenSet,
      'lamp': Iconsax.lamp,
      'utensils': FontAwesomeIcons.utensils,
    },
    'Finance': {
      'money': FontAwesomeIcons.moneyBill,
      'coins': FontAwesomeIcons.coins,
      'credit_card': FontAwesomeIcons.creditCard,
      'bitcoin': FontAwesomeIcons.bitcoin,
      'ethereum': FontAwesomeIcons.ethereum,
      'piggy_bank': FontAwesomeIcons.piggyBank,
      'chart_line': FontAwesomeIcons.chartLine,
      'chart_pie': FontAwesomeIcons.chartPie,
      'calculator': FontAwesomeIcons.calculator,
      'receipt': FontAwesomeIcons.receipt,
      'wallet': Iconsax.wallet,
      'bank': FontAwesomeIcons.buildingColumns,
    },
    'Sports': {
      'football': FontAwesomeIcons.football,
      'basketball': FontAwesomeIcons.basketball,
      'baseball': FontAwesomeIcons.baseball,
      'tennis': FontAwesomeIcons.tableTennisPaddleBall,
      'volleyball': FontAwesomeIcons.volleyball,
      'golf': FontAwesomeIcons.golfBallTee,
      'bowling': FontAwesomeIcons.bowlingBall,
      'hockey': FontAwesomeIcons.hockeyPuck,
      'martial_arts': FontAwesomeIcons.handFist,
      'trophy': FontAwesomeIcons.trophy,
      'medal': Iconsax.medal,
      'stopwatch': FontAwesomeIcons.stopwatch,
    },
    'Art & Creativity': {
      'palette': FontAwesomeIcons.palette,
      'brush': FontAwesomeIcons.brush,
      'paint_brush': FontAwesomeIcons.paintbrush,
      'scissors': FontAwesomeIcons.scissors,
      'pen': FontAwesomeIcons.pen,
      'guitar': FontAwesomeIcons.guitar,
      'drum': FontAwesomeIcons.drum,
      'camera': Iconsax.camera,
      'microphone': FontAwesomeIcons.microphone,
      'theater': FontAwesomeIcons.masksTheater,
      'puzzle': FontAwesomeIcons.puzzlePiece,
      'quill': FontAwesomeIcons.featherPointed,
    },
    'Communication': {
      'message': Iconsax.message,
      'envelope': FontAwesomeIcons.envelope,
      'phone': FontAwesomeIcons.phone,
      'voicemail': FontAwesomeIcons.voicemail,
      'at': FontAwesomeIcons.at,
      'hashtag': FontAwesomeIcons.hashtag,
      'megaphone': FontAwesomeIcons.bullhorn,
      'podcast': FontAwesomeIcons.podcast,
      'blog': FontAwesomeIcons.blog,
      'newspaper': FontAwesomeIcons.newspaper,
      'language': FontAwesomeIcons.language,
      'translate': FontAwesomeIcons.earthAsia,
    },
    'Tools & Utilities': {
      'tools': FontAwesomeIcons.screwdriverWrench,
      'hammer': FontAwesomeIcons.hammer,
      'key': FontAwesomeIcons.key,
      'lock': FontAwesomeIcons.lock,
      'unlock': FontAwesomeIcons.unlock,
      'shield': Iconsax.shield,
      'fire_extinguisher': FontAwesomeIcons.fireExtinguisher,
      'hardhat': FontAwesomeIcons.helmetSafety,
      'ruler_combined': FontAwesomeIcons.rulerCombined,
      'blueprint': FontAwesomeIcons.drawPolygon,
      'wrench': FontAwesomeIcons.wrench,
      'toolbox': FontAwesomeIcons.toolbox,
    },
    'Clothing & Fashion': {
      'shirt': FontAwesomeIcons.shirt,
      'socks': FontAwesomeIcons.socks,
      'glasses': FontAwesomeIcons.glasses,
      'crown': Iconsax.crown,
      'jewelry': FontAwesomeIcons.gem,
      'watch': Iconsax.watch,
      'ring': FontAwesomeIcons.ring,
      'shoe': FontAwesomeIcons.shoePrints,
      'hat': FontAwesomeIcons.hatCowboy,
      'backpack': FontAwesomeIcons.shirtsinbulk,
      'tshirt': FontAwesomeIcons.shirt,
      'gloves': FontAwesomeIcons.mitten,
    },
    'Events & Occasions': {
      'birthday': FontAwesomeIcons.cakeCandles,
      'gift': Iconsax.gift,
      'wedding': FontAwesomeIcons.ring,
      'calendar': Iconsax.calendar,
      'party': FontAwesomeIcons.champagneGlasses,
      'graduation': FontAwesomeIcons.graduationCap,
      'baby': FontAwesomeIcons.baby,
      'holiday': FontAwesomeIcons.planeUp,
      'anniversary': FontAwesomeIcons.award,
      'funeral': FontAwesomeIcons.cross,
      'conference': FontAwesomeIcons.peopleGroup,
      'ceremony': FontAwesomeIcons.medal,
    },
  };
  static Map<String, dynamic> get flattenedIcons {
    final Map<String, dynamic> result = {};

    // Loop through each category in the icons map
    for (final category in icons.entries) {
      final Map<String, dynamic> iconMap = category.value;
      for (final iconEntry in iconMap.entries) {
        result[iconEntry.key] = iconEntry.value;
      }
    }

    return result;
  }

  static const Map<String, Color> colors = {
    'red': Color(0xFFE57373),
    'pink': Color(0xFFF06292),
    'purple': Color(0xFFBA68C8),
    'deepPurple': Color(0xFF9575CD),
    'indigo': Color(0xFF7986CB),
    'blue': Color(0xFF64B5F6),
    'lightBlue': Color(0xFF4FC3F7),
    'cyan': Color(0xFF4DD0E1),
    'teal': Color(0xFF4DB6AC),
    'green': Color(0xFF81C784),
    'lightGreen': Color(0xFFAED581),
    'orange': Color(0xFFFFB74D),
    'deepOrange': Color(0xFFFF8A65),
    'brown': Color(0xFFA1887F),
    'blueGrey': Color(0xFF90A4AE),
    'amber': Color(0xFFFFD54F),
    'yellow': Color(0xFFFFEE58),
    'lime': Color(0xFFD4E157),
    'lightBrown': Color(0xFFBCAAA4),
    'grey': Color(0xFFBDBDBD),
    'darkGrey': Color(0xFF757575),
    'coral': Color(0xFFFF7F50),
    'salmon': Color(0xFFFA8072),
    'crimson': Color(0xFFDC143C),
    'maroon': Color(0xFF800000),
    'fuchsia': Color(0xFFFF00FF),
    'magenta': Color(0xFFFF4081),
    'darkPurple': Color(0xFF673AB7),
    'navy': Color(0xFF3F51B5),
    'royalBlue': Color(0xFF1976D2),
    'skyBlue': Color(0xFF03A9F4),
    'aqua': Color(0xFF00BCD4),
    'mint': Color(0xFF009688),
    'seafoam': Color(0xFF26A69A),
    'emerald': Color(0xFF2E7D32),
    'olive': Color(0xFF689F38),
    'pear': Color(0xFF9CCC65),
    'gold': Color(0xFFFFC107),
    'tangerine': Color(0xFFFF9800),
    'rust': Color(0xFFE64A19),
    'coffee': Color(0xFF795548),
    'slate': Color(0xFF607D8B),
    'charcoal': Color(0xFF455A64),
    'lavender': Color(0xFFB39DDB),
    'periwinkle': Color(0xFF7986CB),
    'turquoise': Color(0xFF26C6DA),
    'jade': Color(0xFF00897B),
    'forest': Color(0xFF388E3C),
    'peach': Color(0xFFFFAB91),
    'apricot': Color(0xFFFFCCBC),
    'rose': Color(0xFFF8BBD0),
    'mauve': Color(0xFFCE93D8),
    'lilac': Color(0xFFD1C4E9),
    'steel': Color(0xFF78909C),
  };

}