import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:iconsax/iconsax.dart';
class IconColorStorage{
  static final Map<String, Map<String, dynamic>> icons = {
    'Common': const {
      'folder': Iconsax.folder,
      'heart': Iconsax.heart,
      'star': Iconsax.star,
      'home': Iconsax.home,
      'calendar': Iconsax.calendar,
      'note': Iconsax.note,
      'clock': Iconsax.clock,
      'bookmark': FontAwesomeIcons.bookmark,
      'bell': FontAwesomeIcons.bell,
      'check': FontAwesomeIcons.check,
      'flag': Iconsax.flag,
      'location': Iconsax.location,
      'message': Iconsax.message,
      'search': FontAwesomeIcons.magnifyingGlass,
      'settings': FontAwesomeIcons.gear,
      'user': FontAwesomeIcons.user,
      'trash': FontAwesomeIcons.trash,
      'edit': FontAwesomeIcons.penToSquare,
      'add': FontAwesomeIcons.plus,
      'minus': FontAwesomeIcons.minus,
      'info': FontAwesomeIcons.circleInfo,
      'warning': FontAwesomeIcons.triangleExclamation,
      'archive': FontAwesomeIcons.boxArchive,
    },
    'Food & Drink': const {
      'coffee': Iconsax.coffee,
      'utensils': FontAwesomeIcons.utensils,
      'burger': FontAwesomeIcons.burger,
      'pizza': FontAwesomeIcons.pizzaSlice,
      'ice_cream': FontAwesomeIcons.iceCream,
      'cookie': FontAwesomeIcons.cookie,
      'apple': FontAwesomeIcons.appleWhole,
      'cheese': FontAwesomeIcons.cheese,
      'bread': FontAwesomeIcons.breadSlice,
      'wine': FontAwesomeIcons.wineBottle,
      'cocktail': FontAwesomeIcons.martiniGlassCitrus,
      'tea': FontAwesomeIcons.mugSaucer,
      'cake': Iconsax.cake,
      'salad': FontAwesomeIcons.leaf,
      'soup': FontAwesomeIcons.bowlRice,
      'steak': FontAwesomeIcons.bacon,
      'fish': FontAwesomeIcons.fish,
      'egg': FontAwesomeIcons.egg,
      'carrot': FontAwesomeIcons.carrot,
      'lemon': FontAwesomeIcons.lemon,
      'pepper': FontAwesomeIcons.pepperHot,
      'bottle': FontAwesomeIcons.bottleWater,
      'grocery': FontAwesomeIcons.basketShopping,
      'restaurant': FontAwesomeIcons.utensils,
      'takeout': FontAwesomeIcons.boxOpen,
    },
    'Transport': {
      'car': Iconsax.car,
      'airplane': Iconsax.airplane,
      'bicycle': FontAwesomeIcons.bicycle,
      'train': FontAwesomeIcons.train,
      'bus': FontAwesomeIcons.bus,
      'ship': FontAwesomeIcons.ship,
      'motorcycle': FontAwesomeIcons.motorcycle,
      'helicopter': FontAwesomeIcons.helicopter,
      'truck': FontAwesomeIcons.truck,
      'subway': FontAwesomeIcons.trainSubway,
      'taxi': FontAwesomeIcons.taxi,
      'uber': FontAwesomeIcons.car,
      'scooter': FontAwesomeIcons.motorcycle,
      'skateboard': FontAwesomeIcons.personSkating,
      'walking': FontAwesomeIcons.personWalking,
      'parking': FontAwesomeIcons.squareParking,
      'traffic': FontAwesomeIcons.trafficLight,
      'road': FontAwesomeIcons.road,
    },
    'Shopping': {
      'cart': Iconsax.shopping_cart,
      'bag': Iconsax.bag,
      'box': Iconsax.box,
      'gift': Iconsax.gift,
      'tag': FontAwesomeIcons.tag,
      'shop': Iconsax.shop,
      'receipt': FontAwesomeIcons.receipt,
      'wallet': Iconsax.wallet,
      'credit_card': FontAwesomeIcons.creditCard,
      'money': FontAwesomeIcons.moneyBill,
      'store': FontAwesomeIcons.store,
      'mall': FontAwesomeIcons.building,
      'online': FontAwesomeIcons.laptop,
      'discount': FontAwesomeIcons.percent,
      'coupon': FontAwesomeIcons.ticket,
      'wishlist': FontAwesomeIcons.heart,
      'compare': FontAwesomeIcons.scaleBalanced,
      'delivery': FontAwesomeIcons.truck,
    },
    'Health & Fitness':  {
      'dumbbell': FontAwesomeIcons.dumbbell,
      'heart_pulse': FontAwesomeIcons.heartPulse,
      'running': FontAwesomeIcons.personRunning,
      'meditation': FontAwesomeIcons.spa,
      'health': Iconsax.health,
      'pills': FontAwesomeIcons.pills,
      'suitcase_medical': FontAwesomeIcons.suitcaseMedical,
      'stethoscope': FontAwesomeIcons.stethoscope,
      'scale': FontAwesomeIcons.weightScale,
      'yoga': FontAwesomeIcons.personPraying,
      'swimming': FontAwesomeIcons.personSwimming,
      'biking': FontAwesomeIcons.personBiking,
      'gym': FontAwesomeIcons.dumbbell,
      'doctor': FontAwesomeIcons.userDoctor,
      'appointment': FontAwesomeIcons.calendarCheck,
      'nutrition': FontAwesomeIcons.appleWhole,
      'water': FontAwesomeIcons.glassWater,
      'sleep': FontAwesomeIcons.bed,
      'steps': FontAwesomeIcons.shoePrints,
    },
    'Education': {
      'book': Iconsax.book,
      'book_open': FontAwesomeIcons.bookOpen,
      'graduation_cap': FontAwesomeIcons.graduationCap,
      'chalkboard': FontAwesomeIcons.chalkboard,
      'pencil': FontAwesomeIcons.pencil,
      'ruler': FontAwesomeIcons.ruler,
      'calculator': FontAwesomeIcons.calculator,
      'teacher': Iconsax.teacher,
      'microscope': FontAwesomeIcons.microscope,
      'flask': FontAwesomeIcons.flask,
      'atom': FontAwesomeIcons.atom,
      'brain': FontAwesomeIcons.brain,
      'school': FontAwesomeIcons.school,
      'student': FontAwesomeIcons.userGraduate,
      'library': FontAwesomeIcons.bookBookmark,
      'homework': FontAwesomeIcons.clipboardList,
      'exam': FontAwesomeIcons.fileCircleQuestion,
      'course': FontAwesomeIcons.chalkboardUser,
      'certificate': FontAwesomeIcons.certificate,
      'research': FontAwesomeIcons.magnifyingGlass,
    },
    'Work & Business': {
      'briefcase': Iconsax.briefcase,
      'chart': Iconsax.chart,
      'chart_line': FontAwesomeIcons.chartLine,
      'task': Iconsax.task_square,
      'building': Iconsax.building,
      'presentation': FontAwesomeIcons.display,
      'handshake': FontAwesomeIcons.handshake,
      'people': FontAwesomeIcons.users,
      'bank': FontAwesomeIcons.buildingColumns,
      'document': FontAwesomeIcons.fileLines,
      'signature': FontAwesomeIcons.signature,
      'network': FontAwesomeIcons.networkWired,
      'meeting': FontAwesomeIcons.usersBetweenLines,
      'deadline': FontAwesomeIcons.clockFour,
      'project': FontAwesomeIcons.folderOpen,
      'client': FontAwesomeIcons.userTie,
      'invoice': FontAwesomeIcons.fileInvoiceDollar,
      'report': FontAwesomeIcons.chartSimple,
      'office': FontAwesomeIcons.buildingUser,
    },
    'Technology': {
      'laptop': FontAwesomeIcons.laptop,
      'mobile': FontAwesomeIcons.mobile,
      'tablet': FontAwesomeIcons.tablet,
      'desktop': FontAwesomeIcons.desktop,
      'code': FontAwesomeIcons.code,
      'microchip': FontAwesomeIcons.microchip,
      'server': FontAwesomeIcons.server,
      'database': FontAwesomeIcons.database,
      'wifi': FontAwesomeIcons.wifi,
      'keyboard': FontAwesomeIcons.keyboard,
      'mouse': FontAwesomeIcons.computerMouse,
      'printer': FontAwesomeIcons.print,
      'cloud': FontAwesomeIcons.cloud,
      'backup': FontAwesomeIcons.hardDrive,
      'bug': FontAwesomeIcons.bug,
      'api': FontAwesomeIcons.plug,
      'security': FontAwesomeIcons.shield,
      'update': FontAwesomeIcons.arrowsRotate,
      'download': FontAwesomeIcons.download,
      'upload': FontAwesomeIcons.upload,
    },
    'Entertainment':  {
      'music': Iconsax.music,
      'video': Iconsax.video,
      'game': Iconsax.game,
      'headphone': Iconsax.headphone,
      'film': FontAwesomeIcons.film,
      'ticket': Iconsax.ticket,
      'theater': FontAwesomeIcons.masksTheater,
      'tv': FontAwesomeIcons.tv,
      'camera': Iconsax.camera,
      'dice': FontAwesomeIcons.dice,
      'gamepad': FontAwesomeIcons.gamepad,
      'vr_headset': FontAwesomeIcons.vrCardboard,
      'concert': FontAwesomeIcons.music,
      'movie': FontAwesomeIcons.clapperboard,
      'streaming': FontAwesomeIcons.play,
      'podcast': FontAwesomeIcons.podcast,
      'book_audio': FontAwesomeIcons.headphones,
      'party': FontAwesomeIcons.champagneGlasses,
    },
    'Travel & Places': const {
      'map': Iconsax.map,
      'compass': FontAwesomeIcons.compass,
      'hotel': FontAwesomeIcons.bed,
      'suitcase': FontAwesomeIcons.suitcaseRolling,
      'passport': FontAwesomeIcons.passport,
      'beach': FontAwesomeIcons.umbrellaBeach,
      'mountain': FontAwesomeIcons.mountain,
      'camping': FontAwesomeIcons.campground,
      'binoculars': FontAwesomeIcons.binoculars,
      'earth': FontAwesomeIcons.earthAmericas,
      'signpost': FontAwesomeIcons.signsPost,
      'luggage_cart': FontAwesomeIcons.cartFlatbedSuitcase,
      'flight': FontAwesomeIcons.plane,
      'destination': FontAwesomeIcons.locationDot,
      'adventure': FontAwesomeIcons.personHiking,
      'tour': FontAwesomeIcons.route,
      'booking': FontAwesomeIcons.calendarDays,
      'visa': FontAwesomeIcons.idCard,
      'currency': FontAwesomeIcons.coins,
    },
    'Nature & Weather': const {
      'tree': Iconsax.tree,
      'pet': Iconsax.pet,
      'plant': FontAwesomeIcons.seedling,
      'sun': FontAwesomeIcons.sun,
      'moon': FontAwesomeIcons.moon,
      'cloud': FontAwesomeIcons.cloud,
      'snowflake': FontAwesomeIcons.snowflake,
      'fire': FontAwesomeIcons.fire,
      'wind': FontAwesomeIcons.wind,
      'rainbow': FontAwesomeIcons.rainbow,
      'leaf': FontAwesomeIcons.leaf,
      'water': FontAwesomeIcons.water,
      'flower': FontAwesomeIcons.spa,
      'butterfly': FontAwesomeIcons.seedling,
      'bird': FontAwesomeIcons.dove,
      'forest': FontAwesomeIcons.tree,
      'garden': FontAwesomeIcons.seedling,
      'thunderstorm': FontAwesomeIcons.cloudBolt,
      'temperature': FontAwesomeIcons.thermometer,
      'humidity': FontAwesomeIcons.droplet,
    },
    'Home & Living': const {
      'couch': FontAwesomeIcons.couch,
      'bed': FontAwesomeIcons.bed,
      'chair': FontAwesomeIcons.chair,
      'soap': FontAwesomeIcons.soap,
      'shower': FontAwesomeIcons.shower,
      'toilet': FontAwesomeIcons.toilet,
      'lightbulb': FontAwesomeIcons.lightbulb,
      'broom': FontAwesomeIcons.broom,
      'fan': FontAwesomeIcons.fan,
      'kitchen': FontAwesomeIcons.kitchenSet,
      'lamp': Iconsax.lamp,
      'utensils': FontAwesomeIcons.utensils,
      'cleaning': FontAwesomeIcons.sprayCan,
      'laundry': FontAwesomeIcons.shirt,
      'dishes': FontAwesomeIcons.plateWheat,
      'vacuum': FontAwesomeIcons.broom,
      'repair': FontAwesomeIcons.hammer,
      'decoration': FontAwesomeIcons.paintRoller,
      'security': FontAwesomeIcons.houseChimney,
      'maintenance': FontAwesomeIcons.screwdriverWrench,
    },
    'Finance': const {
      'money': FontAwesomeIcons.moneyBill,
      'coins': FontAwesomeIcons.coins,
      'credit_card': FontAwesomeIcons.creditCard,
      'bitcoin': FontAwesomeIcons.bitcoin,
      'ethereum': FontAwesomeIcons.ethereum,
      'piggy_bank': FontAwesomeIcons.piggyBank,
      'chart_line': FontAwesomeIcons.chartLine,
      'chart_pie': FontAwesomeIcons.chartPie,
      'calculator': FontAwesomeIcons.calculator,
      'receipt': FontAwesomeIcons.receipt,
      'wallet': Iconsax.wallet,
      'bank': FontAwesomeIcons.buildingColumns,
      'budget': FontAwesomeIcons.scaleBalanced,
      'savings': FontAwesomeIcons.piggyBank,
      'expense': FontAwesomeIcons.minus,
      'income': FontAwesomeIcons.plus,
      'tax': FontAwesomeIcons.fileInvoiceDollar,
      'loan': FontAwesomeIcons.handHoldingDollar,
    },
    'Sports': const {
      'football': FontAwesomeIcons.football,
      'basketball': FontAwesomeIcons.basketball,
      'baseball': FontAwesomeIcons.baseball,
      'tennis': FontAwesomeIcons.tableTennisPaddleBall,
      'volleyball': FontAwesomeIcons.volleyball,
      'golf': FontAwesomeIcons.golfBallTee,
      'bowling': FontAwesomeIcons.bowlingBall,
      'hockey': FontAwesomeIcons.hockeyPuck,
      'martial_arts': FontAwesomeIcons.handFist,
      'trophy': FontAwesomeIcons.trophy,
      'medal': Iconsax.medal,
      'stopwatch': FontAwesomeIcons.stopwatch,
      'soccer': FontAwesomeIcons.futbol,
      'cricket': FontAwesomeIcons.baseball,
      'badminton': FontAwesomeIcons.tableTennisPaddleBall,
      'swimming_pool': FontAwesomeIcons.personSwimming,
      'track': FontAwesomeIcons.personRunning,
      'gym_membership': FontAwesomeIcons.idBadge,
      'coaching': FontAwesomeIcons.chalkboardUser,
    },
    'Art & Creativity': const {
      'palette': FontAwesomeIcons.palette,
      'brush': FontAwesomeIcons.brush,
      'paint_brush': FontAwesomeIcons.paintbrush,
      'scissors': FontAwesomeIcons.scissors,
      'pen': FontAwesomeIcons.pen,
      'guitar': FontAwesomeIcons.guitar,
      'drum': FontAwesomeIcons.drum,
      'camera': Iconsax.camera,
      'microphone': FontAwesomeIcons.microphone,
      'theater': FontAwesomeIcons.masksTheater,
      'puzzle': FontAwesomeIcons.puzzlePiece,
      'quill': FontAwesomeIcons.featherPointed,
      'drawing': FontAwesomeIcons.penRuler,
      'sculpting': FontAwesomeIcons.hammer,
      'crafting': FontAwesomeIcons.scissors,
      'writing': FontAwesomeIcons.penFancy,
      'photography': FontAwesomeIcons.cameraRetro,
      'singing': FontAwesomeIcons.microphoneLines,
    },
    'Communication': const {
      'message': Iconsax.message,
      'envelope': FontAwesomeIcons.envelope,
      'phone': FontAwesomeIcons.phone,
      'voicemail': FontAwesomeIcons.voicemail,
      'at': FontAwesomeIcons.at,
      'hashtag': FontAwesomeIcons.hashtag,
      'megaphone': FontAwesomeIcons.bullhorn,
      'podcast': FontAwesomeIcons.podcast,
      'blog': FontAwesomeIcons.blog,
      'newspaper': FontAwesomeIcons.newspaper,
      'language': FontAwesomeIcons.language,
      'translate': FontAwesomeIcons.earthAsia,
      'video_call': FontAwesomeIcons.video,
      'chat': FontAwesomeIcons.comments,
      'social_media': FontAwesomeIcons.shareNodes,
      'broadcast': FontAwesomeIcons.radio,
      'newsletter': FontAwesomeIcons.newspaper,
      'feedback': FontAwesomeIcons.commentDots,
      'announcement': FontAwesomeIcons.bullhorn,
    },
    'Tools & Utilities': const {
      'tools': FontAwesomeIcons.screwdriverWrench,
      'hammer': FontAwesomeIcons.hammer,
      'key': FontAwesomeIcons.key,
      'lock': FontAwesomeIcons.lock,
      'unlock': FontAwesomeIcons.unlock,
      'shield': Iconsax.shield,
      'fire_extinguisher': FontAwesomeIcons.fireExtinguisher,
      'hardhat': FontAwesomeIcons.helmetSafety,
      'ruler_combined': FontAwesomeIcons.rulerCombined,
      'blueprint': FontAwesomeIcons.drawPolygon,
      'wrench': FontAwesomeIcons.wrench,
      'toolbox': FontAwesomeIcons.toolbox,
      'screwdriver': FontAwesomeIcons.screwdriver,
      'pliers': FontAwesomeIcons.hammer,
      'drill': FontAwesomeIcons.screwdriverWrench,
      'saw': FontAwesomeIcons.hammer,
      'measuring': FontAwesomeIcons.ruler,
      'battery': FontAwesomeIcons.batteryFull,
    },
    'Clothing & Fashion': const {
      'shirt': FontAwesomeIcons.shirt,
      'socks': FontAwesomeIcons.socks,
      'glasses': FontAwesomeIcons.glasses,
      'crown': Iconsax.crown,
      'jewelry': FontAwesomeIcons.gem,
      'watch': Iconsax.watch,
      'ring': FontAwesomeIcons.ring,
      'shoe': FontAwesomeIcons.shoePrints,
      'hat': FontAwesomeIcons.hatCowboy,
      'backpack': FontAwesomeIcons.shirtsinbulk,
      'tshirt': FontAwesomeIcons.shirt,
      'gloves': FontAwesomeIcons.mitten,
      'dress': FontAwesomeIcons.shirt,
      'pants': FontAwesomeIcons.shirt,
      'jacket': FontAwesomeIcons.shirt,
      'shoes': FontAwesomeIcons.shoePrints,
      'handbag': FontAwesomeIcons.bagShopping,
      'sunglasses': FontAwesomeIcons.glasses,
    },
    'Events & Occasions': const {
      'birthday': FontAwesomeIcons.cakeCandles,
      'gift': Iconsax.gift,
      'wedding': FontAwesomeIcons.ring,
      'calendar': Iconsax.calendar,
      'party': FontAwesomeIcons.champagneGlasses,
      'graduation': FontAwesomeIcons.graduationCap,
      'baby': FontAwesomeIcons.baby,
      'holiday': FontAwesomeIcons.planeUp,
      'anniversary': FontAwesomeIcons.award,
      'funeral': FontAwesomeIcons.cross,
      'conference': FontAwesomeIcons.peopleGroup,
      'ceremony': FontAwesomeIcons.medal,
      'reunion': FontAwesomeIcons.usersBetweenLines,
      'celebration': FontAwesomeIcons.champagneGlasses,
      'invitation': FontAwesomeIcons.envelope,
      'rsvp': FontAwesomeIcons.calendarCheck,
      'venue': FontAwesomeIcons.mapLocationDot,
      'planning': FontAwesomeIcons.listCheck,
    },
    'Habit': const {
      'habit': FontAwesomeIcons.repeat,
      'routine': FontAwesomeIcons.clockRotateLeft,
      'daily': FontAwesomeIcons.calendarDay,
      'weekly': FontAwesomeIcons.calendarWeek,
      'monthly': FontAwesomeIcons.calendar,
      'streak': FontAwesomeIcons.fire,
      'progress': FontAwesomeIcons.chartLine,
      'goal': FontAwesomeIcons.bullseye,
      'reminder': FontAwesomeIcons.bell,
      'tracking': FontAwesomeIcons.chartSimple,
      'consistency': FontAwesomeIcons.checkDouble,
      'milestone': FontAwesomeIcons.flagCheckered,
      'challenge': FontAwesomeIcons.mountain,
      'commitment': FontAwesomeIcons.handshake,
      'discipline': FontAwesomeIcons.medal,
      'practice': FontAwesomeIcons.arrowsRotate,
      'timer': FontAwesomeIcons.stopwatch,
      'checklist': FontAwesomeIcons.listCheck,
    },
  };
  static Map<String, dynamic> get flattenedIcons {
    final Map<String, dynamic> result = {};

    // Loop through each category in the icons map
    for (final category in icons.entries) {
      final Map<String, dynamic> iconMap = category.value;
      for (final iconEntry in iconMap.entries) {
        result[iconEntry.key] = iconEntry.value;
      }
    }

    return result;
  }

  static const Map<String, Color> colors = {
    // Primary blues - excellent readability
    'blue': Color(0xFF2196F3),
    'lightBlue': Color(0xFF03A9F4),
    'navy': Color(0xFF1565C0),
    'slate': Color(0xFF546E7A),

    // Greens - calming and accessible
    'green': Color(0xFF4CAF50),
    'teal': Color(0xFF009688),
    'emerald': Color(0xFF00695C),
    'mint': Color(0xFF26A69A),

    // Warm colors - balanced saturation
    'orange': Color(0xFFFF9800),
    'amber': Color(0xFFFFC107),
    'coral': Color(0xFFFF7043),
    'peach': Color(0xFFFFAB40),

    // Purples - sophisticated and easy on eyes
    'purple': Color(0xFF9C27B0),
    'indigo': Color(0xFF3F51B5),
    'lavender': Color(0xFF7986CB),
    'deepPurple': Color(0xFF673AB7),

    // Reds - muted for better accessibility
    'red': Color(0xFFF44336),
    'pink': Color(0xFFE91E63),
    'rose': Color(0xFFAD1457),
    'crimson': Color(0xFFD32F2F),

    // Yellows - adjusted brightness
    'yellow': Color(0xFFFDD835),
    'lime': Color(0xFF689F38),
    'gold': Color(0xFFFF8F00),

    // Neutrals - perfect contrast ratios
    'grey': Color(0xFF757575),
    'darkGrey': Color(0xFF424242),
    'charcoal': Color(0xFF37474F),
    'steel': Color(0xFF607D8B),

    // Nature tones - soothing
    'brown': Color(0xFF8D6E63),
    'coffee': Color(0xFF5D4037),
    'olive': Color(0xFF827717),
    'forest': Color(0xFF2E7D32),

    // Cool tones - modern and accessible
    'cyan': Color(0xFF00BCD4),
    'turquoise': Color(0xFF00ACC1),
    'aqua': Color(0xFF0097A7),
    'jade': Color(0xFF00796B),
  };

}