#file: noinspection SpellCheckingInspection
name: darrt
description: "A simple yet powerful todo and notes app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 25.1.4+26

environment:
  sdk: ^3.8.1

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.

dependencies:
  sentry_flutter: ^9.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  page_transition: ^2.2.1
  intl: ^0.19.0
  awesome_notifications_core: any
  awesome_notifications: ^0.10.1
  toastification: ^3.0.2
  logger: ^2.5.0
  font_awesome_flutter: ^10.8.0
  flex_color_scheme: ^8.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  path: ^1.9.0
  path_provider: ^2.1.5
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  freezed_annotation: ^3.0.0
  flutter_quill: ^11.4.0
  flutter_quill_extensions: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0
  pdf: ^3.11.3
  flutter_quill_to_pdf: ^2.3.7
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  archive: ^4.0.7
  http: ^1.4.0
  workmanager: ^0.9.0
  collection: ^1.19.1
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.7.2
  googleapis_auth: ^2.0.0
  audioplayers: ^6.5.0
  file_picker: ^10.2.0
  google_mobile_ads: ^6.0.0
  just_audio: ^0.10.4
  audio_service: ^0.18.18
  fl_chart: ^1.0.0
  confetti: ^0.8.0
  device_preview: ^1.3.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  purchases_flutter: ^9.2.0
  purchases_ui_flutter: ^9.2.0
  package_info_plus: ^8.3.1
  in_app_review: ^2.0.10

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  objectbox_generator: ^4.2.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6


dependency_overrides:
  intl: ^0.19.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
#    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  fonts:
     - family: Gabarito
       fonts:
         - asset: assets/fonts/Gabarito-Regular.ttf
           weight: 400
         - asset: assets/fonts/Gabarito-Medium.ttf
           weight: 500
         - asset: assets/fonts/Gabarito-Bold.ttf
           weight: 700
         - asset: assets/fonts/Gabarito-ExtraBold.ttf
           weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: true  # Enables Android platform
#  ios: true      # Enables iOS platform
  image_path: "assets/icon/play_store_512.png"  # Path to your icon image
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#9966CC"
  adaptive_icon_foreground: "assets/icon/play_store_512.png"

flutter_native_splash:
  android: true
#  ios: true
  color: "#9966CC"
  icon_background_color: "#9966CC"
  image: assets/icon/1152.png

#  branding: assets/icon/icon_2.png
#  branding_mode: bottom
  android_12:
    color: "#9966CC"
    image: assets/icon/1152.png
#    icon_background_color: "#9966CC"
#    branding: assets/icon/icon_2.png

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: stellarmotion
